---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/praiskup/example-fedora-konflux-tar?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: example-packages
    appstudio.openshift.io/component: tar-github
    pipelines.appstudio.openshift.io/type: build
  name: tar-github-on-pull-request
  namespace: fedora-on-konflux-tenant
spec:
  params:
    - name: package-name
      value: tar
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "main"
    - name: ociStorage
      value: quay.io/konflux-fedora/fedora-on-konflux-tenant/tar-github:on-pr-{{revision}}
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://gitlab.com/fedora/infrastructure/konflux/rpmbuild-pipeline.git
      - name: revision
        value: "main"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
